apiVersion: v1
kind: Secret
metadata:
  name: activity-postgres-secret
  namespace: tripplanning
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: tripdb-activities