apiVersion: v1
kind: Secret
metadata:
  name: user-postgres-secret
  namespace: tripplanning
  labels:
    app: user-postgres
    slice: s1
type: Opaque
data:
  POSTGRES_USER:     cG9zdGdyZXM=      # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=      # postgres
  POSTGRES_DB:       dHJpcGRiLXVzZXJz  # tripdb-users
