spring:
  application:
    name: booking-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tripplanningdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          prefer_native_enum_types: true

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  data:
    mongodb:
      host: ${SPRING_MONGODB_HOST:tripplanning-mongo}
      port: ${SPRING_MONGODB_PORT:27017}
      database: ${SPRING_MONGODB_DATABASE:tripplanningdb}
    redis:
      host: ${SPRING_DATA_REDIS_HOST:tripplanning-redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:tripplanning-secret-key-for-jwt-token-signing}
  expiration: ${JWT_EXPIRATION:86400000}
