apiVersion: v1
kind: ConfigMap
metadata:
  name: destination-service-configmap
  namespace: tripplanning
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://destination-postgres:5432/tripdb-destinations
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_RABBITMQ_HOST: rabbitmq
  FEIGN_ITINERARY_SERVICE_URL: http://itinerary-service:8080
  FEIGN_USER_SERVICE_URL: http://user-service:8080