apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-postgres-pvc
  namespace: tripplanning
  labels:
    app: user-postgres
    slice: s1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
