apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-service-configmap
  namespace: tripplanning
  labels:
    app: booking-service
    slice: s5

data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://booking-postgres:5432/tripplanningdb"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SPRING_MONGODB_HOST: "tripplanning-mongo"
  SPRING_MONGODB_PORT: "27017"
  SPRING_MONGODB_DATABASE: "tripplanningdb"
  SPRING_DATA_REDIS_HOST: "tripplanning-redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "guest"
  SPRING_RABBITMQ_PASSWORD: "guest"
  FEIGN_USER_SERVICE_URL: "http://user-service:8080"
  FEIGN_ITINERARY_SERVICE_URL: "http://itinerary-service:8080"
  FEIGN_DESTINATION_SERVICE_URL: "http://destination-service:8080"
  M3_MESSAGING_ENABLED: "true"

