apiVersion: v1
kind: Service
metadata:
  name: activity-service
  namespace: tripplanning
spec:
  type: ClusterIP
  selector:
    app: activity-service
  ports:
    - port: 8080
      targetPort: 8080