apiVersion: v1
kind: ConfigMap
metadata:
  name: activity-service-configmap
  namespace: tripplanning
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://activity-postgres:5432/tripplanningdb
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
  FEIGN_ITINERARY_SERVICE_URL: http://itinerary-service:8080
  CASSANDRA_CONTACT_POINTS: cassandra
  CASSANDRA_PORT: "9042"
  CASSANDRA_KEYSPACE: tripplanningks
  CASSANDRA_DATACENTER: datacenter1
  SPRING_MONGODB_HOST: mongo
  SPRING_MONGODB_PORT: "27017"
  SPRING_MONGODB_DATABASE: tripplanningdb
  SPRING_REDIS_HOST: redis
  SPRING_REDIS_PORT: "6379"
  M3_MESSAGING_ENABLED: "true"