apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: itinerary-postgres
  namespace: tripplanning
spec:
  serviceName: itinerary-postgres
  replicas: 1
  selector:
    matchLabels:
      app: itinerary-postgres
  template:
    metadata:
      labels:
        app: itinerary-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: itinerary-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: itinerary-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: itinerary-postgres-secret
                  key: POSTGRES_DB
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "tripdb-itineraries"]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 20
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
